service: angular-jump-start-olga

plugins:
  - serverless-apigw-binary

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  memorySize: 512
  timeout: 30
  apiName: ssr-rw
  cfLogs: true
  deploymentPrefix: jsolga


package:
  exclude:
   - src/**
   - e2e/**
   - node_modules/**
   - cypress/**
   - deno/**
   - api/**

custom:
  apigwBinary:
    types:
      - '*/*'

functions:
  run:
    handler: handler.run
    events:
      - http: ANY {proxy+}
      - http: ANY /

